
heterocycles = {
    "pyrolidinone": "O=C1N([R])C([R])CC1[R]",
    "gamme-butyrrolactone": "O=C1OC([R])CC1[R]",
    "beta-lactone": "O=C1C([R])C([R])O1",
    "beta-lactam": "O=C1C([R])C([R])N1[R]",
    "4-piperidinone": "O=C1C([R])C([R])N([R])C([R])C1[R]",
    "2-piperidinone": "O=C1N([R])C([R])CCC1[R]",
    "pyrrolidine": "[R]N1C([R])CCC1[R]",
    "pyrrole": "[R]N1C([R])=C([R])C([R])=C1[R]",
    "pyrazolidine": "[R]N1N([R])C([R])CC1[R]",
    "piperidine": "[R]C1CC([R])N([R])C([R])C1",
    "pyridine": "[R]C1=C([R])C([R])=C([R])C([R])=N1",
    "pyrazole": "[R]N1C([R])=C([R])C([R])=N1",
    "imidazole": "[R]C1=NC([R])=C([R])N1[R]",
    "pyridazine": "[R]C1=NN=C([R])C([R])=C1[R]",
    "pyrimidine": "[R]C1=NC([R])=C([R])C([R])=N1",
    "pyrazine": "[R]C1=C([R])N=C([R])C([R])=N1",
    "1,2,4-traizole": "[R]C1=NN([R])C([R])=N1",
    "1,2,3-triazole": "[R]N1N=NC([R])=C1[R]",
    "1,2,3-triazine": "[R]C1=NN=C([R])C([R])=N1",
    "1,3,5-triazine": "[R]C1=NC([R])=NC([R])=N1",
    "tetrahydropyran": "[R]C1C([R])CC([R])C([R])O1",
    "Tetrahydrofuran": "[R]C1CCC([R])O1",
    "furan": "[R]C1=C([R])C([R])=C([R])O1",
    "1,4-dioxane": "[R]C1C([R])OC([R])C([R])O1",
    "morpholine": "[R]C1COCC([R])N1[R]",
    "cytosine": "O=C1N([R])C([R])=C([R])C(N[R])=N1",
    "Tetrahydrothiophene": "[R]C1CCC([R])S1",
    "thiophene": "[R]C1=C([R])C([R])=C([R])S1",
    "isoxazole": "[R]C1=NOC([R])=C1[R]",
    "uracil": "O=C(N([R])C([R])=C1[R])N([R])C1=O",
    "pyrrolizidine": "[R]C1CCN2C1C([R])CC2",
    "tetrahydropyranone": "O=C1C([R])COCC1[R]",
    "oxazole": "[R]C1=NC([R])=C([R])O1",
    "thiazole": "[R]C1=C([R])N=C([R])S1",
    "indoline": "[R]N1C2=C([R])C([R])=C([R])C([R])=C2C([R])C1[R]",
    "indole": "[R]N1C2=C([R])C([R])=C([R])C([R])=C2C([R])=C1[R]",
    "cyclohexanone": "O=C1C([R])CC([R])CC1[R]",
    "purine": "[R]C1=NC([R])=C2C(N=C([R])N2[R])=N1",
    "benzofuran": "[R]C1=C2C(C([R])=C([R])O2)=C([R])C([R])=C1[R]",
    "benzothiophene": "[R]C1=C([R])C2=C([R])C([R])=C([R])C([R])=C2S1",
    "benzoisoxazole": "[R]C1=C(ON=C2[R])C2=C([R])C([R])=C1[R]",
    "benzoisothiazole": "[R]C1=NSC2=C([R])C([R])=C([R])C([R])=C21",
    "benzoxazole": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2O1",
    "benzothiazole": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2S1",
    "adenine": "[R]NC1=C2C(N=C([R])N2[R])=NC([R])=N1",
    "quinoline": "[R]C1=C2C(C([R])=C([R])C([R])=N2)=C([R])C([R])=C1[R]",
    "isoquinoline": "[R]C1=C([R])C([R])=C(C([R])=C([R])N=C2[R])C2=C1[R]",
    "quinoxaline": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2N=C1[R]",
    "quinazoline": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2C([R])=N1",
    "cinnoline": "[R]C1=C([R])C2=C([R])C([R])=C([R])C([R])=C2N=N1",
    "pteridine": "[R]C1=NC2=NC([R])=C([R])N=C2C([R])=N1",
    "chromene": "[R]C1=C([R])OC2=C([R])C([R])=C([R])C([R])=C2C1",
    "chromenone": "O=C1C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C2O1",
    "quinolinone": "O=C1C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C2N1[R]",
    "isoquinolinone": "O=C1N([R])C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C21",
    "caprolactam": "O=C1N([R])C([R])CCCC1[R]",
    #"piperazine": "[R]N1CCN([R])CC1",
    #"hydantoin": "O=C1N([R])C([R])C(N1[R])=O",
    #"tetrazole": "[R]C1=NN=NN1[R]",
    #"2-oxazolidone": "O=C1N([R])C([R])CO1",
    #"guanine": "O=C1C2C(N([R])C([R])=N2)N=C(N[R])N1[R]",
    "1": "O=C1C2=C(C([R])=NN2[R])C([R])C([R])N1[R]",
    #"2": "O=C1CCCC(N1[R])=O",
    #"3": "O=C1C([R])OCCN1[R]",
    "4": "O=C1NC2=NC(N[R])=NC([R])=C2C([R])=C1[R]",
    #"5": "[R]N1C([R])C2=NN=C([R])N2CC1",
    #"6": "CC(C(N1[R])=O)(C)N([R])C1=S",
    "7": "O=C1N([R])CCN(C1=C2O[R])C([R])=C([R])C2=O",
    "8": "O=C1N([R])C(C(N=C([R])N2[R])=C2N1[R])=O",
    "9": "O=C1C2=C(N([R])C([R])=C2[R])N([R])C([R])=N1",
    "10": "O=C([R])N1CCN([R])CC1",
    "11": "[R]C1=C([R])C([R])=C([R])C2=C1OCO2",
    "12": "[R]C1=NC2=C(C([R])=C([R])N2[R])C([R])=N1",
    #"13": "O=C1N([R])C(C2C3CCC(C3)C21)=O",
    "14": "O=C1N([R])N=C([R])C2=C([R])C([R])=C([R])C([R])=C21",
    "15": "[R]N1N=NC2=NC([R])=NC([R])=C21",
    "16": "[R]NC1=NC([R])=C([R])S1",
    "17": "O=C1C([R])=C([R])N([R])C2=C([R])C([R])=C([R])C([R])=C21",
    "18": "[R]N1CCC2=C([R])C([R])=C([R])C([R])=C2C1[R]",
    "19": "O=C1OC([R])=C([R])O1",
    #"20": "O=C1N([R])N=C([R])N1[R]",
    "21": "O=C(OC)C1=C([R])N([R])C([R])=C(C(OC)=O)C1[R]",
    }

functionalized_arenes = {
    "aniline": "[R]NC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "catechol": "[R]OC1=C([R])C([R])=C([R])C([R])=C1O[R]",
    "recorcinol": "[R]OC1=C([R])C([R])=C([R])C(O[R])=C1[R]",
    "hydroquinone": "[R]OC1=C([R])C([R])=C(O[R])C([R])=C1[R]",
    "anisole": "[R]C1=C([R])C([R])=C([R])C([R])=C1OC",
    "benzaldehyde": "O=C([R])C1=C([R])C([R])=C([R])C([R])=C1[R]",
    "benzamide": "O=C(N[R])C1=C([R])C([R])=C([R])C([R])=C1[R]",
    "formanalide": "O=C([R])N([R])C1=C([R])C([R])=C([R])C([R])=C1[R]",
    "trifluotoluene": "[R]C1=C(C(F)(F)F)C([R])=C([R])C([R])=C1[R]",
    "chlorobenzene": "ClC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "fluorobenzene": "FC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "benzoic acid": "O=C(O[R])C1=C([R])C([R])=C([R])C([R])=C1[R]",
    "benzensulfonamide": "O=S(C1=C([R])C([R])=C([R])C([R])=C1[R])(N[R])=O",
    "phenol": "[R]OC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "Iodobenzene": "IC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "Bromobenzene": "BrC1=C([R])C([R])=C([R])C([R])=C1[R]",
    }

functional_groups = {
    "phosphoramidate": "O=P(O[R])(N[R])[R]",
    "phosphate": "O=P(O[R])(O[R])[R]",
    "Urea": "O=C(N[R])N[R]",
    "Thiourea": "S=C(N[R])N[R]",
    "carbamate": "O=C(N[R])O[R]",
    "Cyano": "[R]C#N",
    "Sulfoxide": "O=S([R])[R]",
    "trifluoromethyl": "[R]C(F)(F)F",
    "sulfonamide": "O=S(N[R])([R])=O",
    "Carboxylic acid": "O=C([R])O",
    "Ester": "O=C([R])O[R]",
    "amide": "[R]N([R])C([R])=O",
    "Thiyl": "S[R]",
    "Sulfone": "O=S([R])([R])=O",
    "Crotyl": "C/C=C/[R]",
    "1,3-dioxolane": "[R]C1OCCO1",
    "Trans-vinyl": "[R]/C=C/[R]",
    "cis-vinyl": "[R]/C=C\[R]",
    "sulfonic acid": "O=S(O)([R])=O",
    "guanidine": "N=C(N[R])N[R]",
    "amidine": "N=C([R])N[R]",
    "epoxide": "[R]C1OC1[R]",
    "cyclopropane": "[R]C1CC1",
    "isopropyl": "[R]C(C)C",
    "tert-butyl": "[R]C(C)(C)C",
    "Formyl": "O=C[R]",
    "methoxy": "CO[R]",
    "hydoxyl": "O[R]",
    "Amine": "N[R]",
    "Fluro": "F[R]",
    "Chloro": "Cl[R]",
    "Bromo": "Br[R]",
    "Iodo": "I[R]",
    "Propyl": "[R]CCC[R]",
    "Ethyl": "[R]CC[R]",
    "Methyl": "C[R]",
    }

hydrocarbons = {
    "naphthalene": "[R]C1=C([R])C([R])=C2C(C([R])=C([R])C([R])=C2[R])=C1[R]",
    "cyclohexane": "[R]C1C([R])C([R])C([R])C([R])C1[R]",
    "cyclopentane": "[R]C1C([R])C([R])C([R])C1[R]",
    "cyclobutane": "[R]C1C([R])C([R])C1[R]",
    "toluene": "[R]CC1=C([R])C([R])=C([R])C([R])=C1[R]",
    "addamantyl": "[R]C1(CC2([R])C3)CC(C2)([R])CC3([R])C1",
    "benzene": "[R]C1=C([R])C([R])=C([R])C([R])=C1[R]",
    }

amines = {
    "Methylamine": "CN[R]",
    "dimethylamine": "CN([R])C",
    "diethylamine": "CCN([R])CC",
    "propylamine": "CCCN[R]",
    "cyclopropylamine": "[R]NC1CC1",
    "isopropylamine": "CC(C)N[R]",
    "t-butylamine": "CC(C)(C)N[R]",
    "Benzylamine": "[R]NCC1=CC=CC=C1",
    }

linkers = {
    "Pentyl": "[R]CCCCC[R]",
    "Butyl": "[R]CCCC[R]",
    "Aminoethanol": "[R]NCCO[R]",
    "Glycerol": "[R]OCC(CO[R])O[R]",
    "Ethylene Glycol": "[R]OCCO[R]",
    }

amino_acids = {
    "Methionine": "N[C@H](C(O)=O)CCSC",
    "Tyrosine": "N[C@H](C(O)=O)CC1=CC=C(O)C=C1",
    "Phenylalanine": "N[C@H](C(O)=O)CC1=CC=CC=C1",
    "Tryptophan": "N[C@H](C(O)=O)CC1=CNC2=C1C=CC=C2",
    "Asparagine": "N[C@H](C(O)=O)CC(N)=O",
    "Glutamine": "N[C@H](C(O)=O)CCC(N)=O",
    "Cysteine": "N[C@H](C(O)=O)CS",
    "Lysine": "N[C@H](C(O)=O)CCCCN",
    "Aspartic Acid": "N[C@H](C(O)=O)CC(O)=O",
    "Glutamic Acid": "N[C@H](C(O)=O)CCC(O)=O",
    "Histidine": "N[C@H](C(O)=O)CC1=CNC=N1",
    "Arginine": "N[C@H](C(O)=O)CCCNC(N)=N",
    "Tert-Leucine": "N[C@H](C(O)=O)C(C)(C)C",
    "Cyclopropyl-Glycine": "N[C@H](C(O)=O)C1CC1",
    "Pyroglutamic acid": "OC([C@H](CC1)NC1=O)=O",
    "Proline": "OC([C@H]1NCCC1)=O",
    "Isoleucine": "N[C@@H]([C@@H](CC)C)C(O)=O",
    "Valine": "N[C@H](C(O)=O)C(C)C",
    "Leucine": "N[C@H](C(O)=O)CC(C)C",
    "Threonine": "N[C@H](C(O)=O)[C@@H](C)O",
    "Serine": "N[C@H](C(O)=O)CO",
    "Alanine": "N[C@H](C(O)=O)C",
    "Glycine": "NCC(O)=O",
    }

# program these with R groups
# write smiles_to_structure addendum that interprets R group as turn can bond to True
# under build_fragments, when bond get's added to, turn can bond to false if atom.bonded_to >= 3
# (that way primary atoms will be able to bond twice)

