
heterocycles = {"pyrolidinone": "O=C1N([R])C([R])CC1[R]",
                "gamme-butyrrolactone": "O=C1OC([R])CC1[R]",
                "beta-lactone": "O=C1C([R])C([R])O1",
                "beta-lactam": "O=C1C([R])C([R])N1[R]",
                "4-piperidinone": "O=C1C([R])C([R])N([R])C([R])C1[R]",
                "2-piperidinone": "O=C1N([R])C([R])CCC1[R]",
                "pyrrolidine": "[R]N1C([R])CCC1[R]",
                "pyrrole": "[R]N1C([R])=C([R])C([R])=C1[R]",
                "pyrazolidine": "[R]N1N([R])C([R])CC1[R]",
                "piperidine": "[R]C1CC([R])N([R])C([R])C1",
                "pyridine": "[R]C1=C([R])C([R])=C([R])C([R])=N1",
                #"piperazine": "[R]N1CCN([R])CC1",
                "pyrazole": "[R]N1C([R])=C([R])C([R])=N1",
                "imidazole": "[R]C1=NC([R])=C([R])N1[R]",
                "pyridazine": "[R]C1=NN=C([R])C([R])=C1[R]",
                "pyrimidine": "[R]C1=NC([R])=C([R])C([R])=N1",
                "pyrazine": "[R]C1=C([R])N=C([R])C([R])=N1",
                "1,2,4-traizole": "[R]C1=NN([R])C([R])=N1",
                "1,2,3-triazole": "[R]N1N=NC([R])=C1[R]",
                #"tetrazole": "[R]C1=NN=NN1[R]",
                "1,2,3-triazine": "[R]C1=NN=C([R])C([R])=N1",
                "1,3,5-triazine": "[R]C1=NC([R])=NC([R])=N1",
                "tetrahydropyran": "[R]C1C([R])CC([R])C([R])O1",
                "Tetrahydrofuran": "[R]C1CCC([R])O1",
                "furan": "[R]C1=C([R])C([R])=C([R])O1",
                "1,4-dioxane": "[R]C1C([R])OC([R])C([R])O1",
                "morpholine": "[R]C1COCC([R])N1[R]",
                "cytosine": "O=C1N([R])C([R])=C([R])C(N[R])=N1",
                "Tetrahydrothiophene": "[R]C1CCC([R])S1",
                "thiophene": "[R]C1=C([R])C([R])=C([R])S1",
                "isoxazole": "[R]C1=NOC([R])=C1[R]",
                "uracil": "O=C(N([R])C([R])=C1[R])N([R])C1=O",
                "pyrrolizidine": "[R]C1CCN2C1C([R])CC2",
                "tetrahydropyranone": "O=C1C([R])COCC1[R]",
                "oxazole": "[R]C1=NC([R])=C([R])O1",
                "thiazole": "[R]C1=C([R])N=C([R])S1",
                "2-oxazolidone": "O=C1N([R])C([R])CO1",
                #"hydantoin": "O=C1N([R])C([R])C(N1[R])=O",
                "indoline": "[R]N1C2=C([R])C([R])=C([R])C([R])=C2C([R])C1[R]",
                "indole": "[R]N1C2=C([R])C([R])=C([R])C([R])=C2C([R])=C1[R]",
                "cyclohexanone": "O=C1C([R])CC([R])CC1[R]",
                "purine": "[R]C1=NC([R])=C2C(N=C([R])N2[R])=N1",
                "benzofuran": "[R]C1=C2C(C([R])=C([R])O2)=C([R])C([R])=C1[R]",
                "benzothiophene": "[R]C1=C([R])C2=C([R])C([R])=C([R])C([R])=C2S1",
                "benzoisoxazole": "[R]C1=C(ON=C2[R])C2=C([R])C([R])=C1[R]",
                "benzoisothiazole": "[R]C1=NSC2=C([R])C([R])=C([R])C([R])=C21",
                "benzoxazole": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2O1",
                "benzothiazole": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2S1",
                "adenine": "[R]NC1=C2C(N=C([R])N2[R])=NC([R])=N1",
                "guanine": "O=C1C2C(N([R])C([R])=N2)N=C(N[R])N1[R]",
                "quinoline": "[R]C1=C2C(C([R])=C([R])C([R])=N2)=C([R])C([R])=C1[R]",
                "isoquinoline": "[R]C1=C([R])C([R])=C(C([R])=C([R])N=C2[R])C2=C1[R]",
                "quinoxaline": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2N=C1[R]",
                "quinazoline": "[R]C1=NC2=C([R])C([R])=C([R])C([R])=C2C([R])=N1",
                "cinnoline": "[R]C1=C([R])C2=C([R])C([R])=C([R])C([R])=C2N=N1",
                "pteridine": "[R]C1=NC2=NC([R])=C([R])N=C2C([R])=N1",
                "chromene": "[R]C1=C([R])OC2=C([R])C([R])=C([R])C([R])=C2C1",
                "chromenone": "O=C1C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C2O1",
                "quinolinone": "O=C1C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C2N1[R]",
                "isoquinolinone": "O=C1N([R])C([R])=C([R])C2=C([R])C([R])=C([R])C([R])=C21",
                "caprolactam": "O=C1N([R])C([R])CCCC1[R]",
                }

# program these with R groups
# write smiles_to_structure addendum that interprets R group as turn can bond to True
# under build_fragments, when bond get's added to, turn can bond to false if atom.bonded_to >= 3
# (that way primary atoms will be able to bond twice)

