
# TODO Crotyl/ and vinyl not working properly(the cis or trans bond to [R] group is not preserved because the R group gets removed

heterocycles = {
    "pyrolidinone": "O=C1N(E)C(E)CC1E",
    "gamme-butyrrolactone": "O=C1OC(E)CC1E",
    "beta-lactone": "O=C1C(E)C(E)O1",
    "beta-lactam": "O=C1C(E)C(E)N1E",
    "4-piperidinone": "O=C1C(E)C(E)N(E)C(E)C1E",
    "2-piperidinone": "O=C1N(E)C(E)CCC1E",
    "pyrrolidine": "EN1C(E)CCC1E",
    "pyrrole": "EN1C(E)=C(E)C(E)=C1E",
    "pyrazolidine": "EN1N(E)C(E)CC1E",
    "piperidine": "EC1CC(E)N(E)C(E)C1",
    "pyridine": "EC1=C(E)C(E)=C(E)C(E)=N1",
    "pyrazole": "EN1C(E)=C(E)C(E)=N1",
    "imidazole": "EC1=NC(E)=C(E)N1E",
    "pyridazine": "EC1=NN=C(E)C(E)=C1E",
    "pyrimidine": "EC1=NC(E)=C(E)C(E)=N1",
    "pyrazine": "EC1=C(E)N=C(E)C(E)=N1",
    "1,2,4-traizole": "EC1=NN(E)C(E)=N1",
    "1,2,3-triazole": "EN1N=NC(E)=C1E",
    "1,2,3-triazine": "EC1=NN=C(E)C(E)=N1",
    "1,3,5-triazine": "EC1=NC(E)=NC(E)=N1",
    "tetrahydropyran": "EC1C(E)CC(E)C(E)O1",
    "Tetrahydrofuran": "EC1CCC(E)O1",
    "furan": "EC1=C(E)C(E)=C(E)O1",
    "1,4-dioxane": "EC1C(E)OC(E)C(E)O1",
    "morpholine": "EC1COCC(E)N1E",
    "cytosine": "O=C1N(E)C(E)=C(E)C(NE)=N1",
    "Tetrahydrothiophene": "EC1CCC(E)S1",
    "thiophene": "EC1=C(E)C(E)=C(E)S1",
    "isoxazole": "EC1=NOC(E)=C1E",
    "uracil": "O=C(N(E)C(E)=C1E)N(E)C1=O",
    "pyrrolizidine": "EC1CCN2C1C(E)CC2",
    "tetrahydropyranone": "O=C1C(E)COCC1E",
    "oxazole": "EC1=NC(E)=C(E)O1",
    "thiazole": "EC1=C(E)N=C(E)S1",
    "indoline": "EN1C2=C(E)C(E)=C(E)C(E)=C2C(E)C1E",
    "indole": "EN1C2=C(E)C(E)=C(E)C(E)=C2C(E)=C1E",
    "cyclohexanone": "O=C1C(E)CC(E)CC1E",
    "purine": "EC1=NC(E)=C2C(N=C(E)N2E)=N1",
    "benzofuran": "EC1=C2C(C(E)=C(E)O2)=C(E)C(E)=C1E",
    "benzothiophene": "EC1=C(E)C2=C(E)C(E)=C(E)C(E)=C2S1",
    "benzoisoxazole": "EC1=C(ON=C2E)C2=C(E)C(E)=C1E",
    "benzoisothiazole": "EC1=NSC2=C(E)C(E)=C(E)C(E)=C21",
    "benzoxazole": "EC1=NC2=C(E)C(E)=C(E)C(E)=C2O1",
    "benzothiazole": "EC1=NC2=C(E)C(E)=C(E)C(E)=C2S1",
    "adenine": "ENC1=C2C(N=C(E)N2E)=NC(E)=N1",
    "quinoline": "EC1=C2C(C(E)=C(E)C(E)=N2)=C(E)C(E)=C1E",
    "isoquinoline": "EC1=C(E)C(E)=C(C(E)=C(E)N=C2E)C2=C1E",
    "quinoxaline": "EC1=NC2=C(E)C(E)=C(E)C(E)=C2N=C1E",
    "quinazoline": "EC1=NC2=C(E)C(E)=C(E)C(E)=C2C(E)=N1",
    "cinnoline": "EC1=C(E)C2=C(E)C(E)=C(E)C(E)=C2N=N1",
    "pteridine": "EC1=NC2=NC(E)=C(E)N=C2C(E)=N1",
    "chromene": "EC1=C(E)OC2=C(E)C(E)=C(E)C(E)=C2C1",
    "chromenone": "O=C1C(E)=C(E)C2=C(E)C(E)=C(E)C(E)=C2O1",
    "quinolinone": "O=C1C(E)=C(E)C2=C(E)C(E)=C(E)C(E)=C2N1E",
    "isoquinolinone": "O=C1N(E)C(E)=C(E)C2=C(E)C(E)=C(E)C(E)=C21",
    "caprolactam": "O=C1N(E)C(E)CCCC1E",
    "1": "O=C1C2=C(C(E)=NN2E)C(E)C(E)N1E",
    "4": "O=C1NC2=NC(NE)=NC(E)=C2C(E)=C1E",
    "7": "O=C1N(E)CCN(C1=C2OE)C(E)=C(E)C2=O",
    "8": "O=C1N(E)C(C(N=C(E)N2E)=C2N1E)=O",
    "9": "O=C1C2=C(N(E)C(E)=C2E)N(E)C(E)=N1",
    "10": "O=C(E)N1CCN(E)CC1",
    "11": "EC1=C(E)C(E)=C(E)C2=C1OCO2",
    "12": "EC1=NC2=C(C(E)=C(E)N2E)C(E)=N1",
    "14": "O=C1N(E)N=C(E)C2=C(E)C(E)=C(E)C(E)=C21",
    "15": "EN1N=NC2=NC(E)=NC(E)=C21",
    "16": "ENC1=NC(E)=C(E)S1",
    "17": "O=C1C(E)=C(E)N(E)C2=C(E)C(E)=C(E)C(E)=C21",
    "18": "EN1CCC2=C(E)C(E)=C(E)C(E)=C2C1E",
    "19": "O=C1OC(E)=C(E)O1",
    "21": "O=C(OC)C1=C(E)N(E)C(E)=C(C(OC)=O)C1E",
    # "piperazine": "EN1CCN(E)CC1",
    # "hydantoin": "O=C1N(E)C(E)C(N1E)=O",
    # "tetrazole": "EC1=NN=NN1E",
    # "2-oxazolidone": "O=C1N(E)C(E)CO1",
    # "guanine": "O=C1C2C(N(E)C(E)=N2)N=C(NE)N1E",
    # "20": "O=C1N(E)N=C(E)N1E",
    # "13": "O=C1N(E)C(C2C3CCC(C3)C21)=O",
    # "5": "EN1C(E)C2=NN=C(E)N2CC1",
    # "6": "CC(C(N1E)=O)(C)N(E)C1=S",
    # "2": "O=C1CCCC(N1E)=O",
    # "3": "O=C1C(E)OCCN1E",
    }

functionalized_arenes = {
    "aniline": "ENC1=C(E)C(E)=C(E)C(E)=C1E",
    "catechol": "EOC1=C(E)C(E)=C(E)C(E)=C1OE",
    "recorcinol": "EOC1=C(E)C(E)=C(E)C(OE)=C1E",
    "hydroquinone": "EOC1=C(E)C(E)=C(OE)C(E)=C1E",
    "anisole": "EC1=C(E)C(E)=C(E)C(E)=C1OC",
    "benzaldehyde": "O=C(E)C1=C(E)C(E)=C(E)C(E)=C1E",
    "benzamide": "O=C(NE)C1=C(E)C(E)=C(E)C(E)=C1E",
    "formanalide": "O=C(E)N(E)C1=C(E)C(E)=C(E)C(E)=C1E",
    "trifluotoluene": "EC1=C(C(F)(F)F)C(E)=C(E)C(E)=C1E",
    "chlorobenzene": "ClC1=C(E)C(E)=C(E)C(E)=C1E",
    "fluorobenzene": "FC1=C(E)C(E)=C(E)C(E)=C1E",
    "benzoic acid": "O=C(OE)C1=C(E)C(E)=C(E)C(E)=C1E",
    "benzensulfonamide": "O=S(C1=C(E)C(E)=C(E)C(E)=C1E)(NE)=O",
    "phenol": "EOC1=C(E)C(E)=C(E)C(E)=C1E",
    "Iodobenzene": "IC1=C(E)C(E)=C(E)C(E)=C1E",
    "Bromobenzene": "BrC1=C(E)C(E)=C(E)C(E)=C1E",
    }

functional_groups = {
    "phosphoramidate": "O=P(OE)(NE)E",
    "phosphate": "O=P(OE)(OE)E",
    "Urea": "O=C(NE)NE",
    "Thiourea": "S=C(NE)NE",
    "carbamate": "O=C(NE)OE",
    "Cyano": "EC#N",
    "Sulfoxide": "O=S(E)E",
    "trifluoromethyl": "EC(F)(F)F",
    "sulfonamide": "O=S(NE)(E)=O",
    "Carboxylic acid": "O=C(E)O",
    "Ester": "O=C(E)OE",
    "amide": "EN(E)C(E)=O",
    "Thiyl": "SE",
    "Sulfone": "O=S(E)(E)=O",
    "Crotyl": "C/C=C/E",
    "1,3-dioxolane": "EC1OCCO1",
    "Trans-vinyl": "E/C=C/E",
    "cis-vinyl": "E/C=C\E",
    "sulfonic acid": "O=S(O)(E)=O",
    "guanidine": "N=C(NE)NE",
    "amidine": "N=C(E)NE",
    "epoxide": "EC1OC1E",
    "cyclopropane": "EC1CC1",
    "isopropyl": "EC(C)C",
    "tert-butyl": "EC(C)(C)C",
    "Formyl": "O=CE",
    "methoxy": "COE",
    "hydoxyl": "OE",
    "Amine": "NE",
    "Fluro": "FE",
    "Chloro": "ClE",
    "Bromo": "BrE",
    "Iodo": "IE",
    "Propyl": "ECCCE",
    "Ethyl": "ECCE",
    "Methyl": "CE",
    }

hydrocarbons = {
    "naphthalene": "EC1=C(E)C(E)=C2C(C(E)=C(E)C(E)=C2E)=C1E",
    "cyclohexane": "EC1C(E)C(E)C(E)C(E)C1E",
    "cyclopentane": "EC1C(E)C(E)C(E)C1E",
    "cyclobutane": "EC1C(E)C(E)C1E",
    "toluene": "ECC1=C(E)C(E)=C(E)C(E)=C1E",
    "addamantyl": "EC1(CC2(E)C3)CC(C2)(E)CC3(E)C1",
    "benzene": "EC1=C(E)C(E)=C(E)C(E)=C1E",
    }

amines = {
    "Methylamine": "CNE",
    "dimethylamine": "CN(E)C",
    "diethylamine": "CCN(E)CC",
    "propylamine": "CCCNE",
    "cyclopropylamine": "ENC1CC1",
    "isopropylamine": "CC(C)NE",
    "t-butylamine": "CC(C)(C)NE",
    "Benzylamine": "ENCC1=CC=CC=C1",
    }

linkers = {
    "Pentyl": "ECCCCCE",
    "Butyl": "ECCCCE",
    "Aminoethanol": "ENCCOE",
    "Glycerol": "EOCC(COE)OE",
    "Ethylene Glycol": "EOCCOE",
    }

amino_acids = {
    "Methionine": "N[C@H](C(O)=O)CCSC",
    "Tyrosine": "N[C@H](C(O)=O)CC1=CC=C(O)C=C1",
    "Phenylalanine": "N[C@H](C(O)=O)CC1=CC=CC=C1",
    "Tryptophan": "N[C@H](C(O)=O)CC1=CNC2=C1C=CC=C2",
    "Asparagine": "N[C@H](C(O)=O)CC(N)=O",
    "Glutamine": "N[C@H](C(O)=O)CCC(N)=O",
    "Cysteine": "N[C@H](C(O)=O)CS",
    "Lysine": "N[C@H](C(O)=O)CCCCN",
    "Aspartic Acid": "N[C@H](C(O)=O)CC(O)=O",
    "Glutamic Acid": "N[C@H](C(O)=O)CCC(O)=O",
    "Histidine": "N[C@H](C(O)=O)CC1=CNC=N1",
    "Arginine": "N[C@H](C(O)=O)CCCNC(N)=N",
    "Tert-Leucine": "N[C@H](C(O)=O)C(C)(C)C",
    "Cyclopropyl-Glycine": "N[C@H](C(O)=O)C1CC1",
    "Pyroglutamic acid": "OC([C@H](CC1)NC1=O)=O",
    "Proline": "OC([C@H]1NCCC1)=O",
    "Isoleucine": "N[C@@H]([C@@H](CC)C)C(O)=O",
    "Valine": "N[C@H](C(O)=O)C(C)C",
    "Leucine": "N[C@H](C(O)=O)CC(C)C",
    "Threonine": "N[C@H](C(O)=O)[C@@H](C)O",
    "Serine": "N[C@H](C(O)=O)CO",
    "Alanine": "N[C@H](C(O)=O)C",
    "Glycine": "NCC(O)=O",
    }

# program these with R groups
# write smiles_to_structure addendum that interprets R group as turn can bond to True
# under build_fragments, when bond get's added to, turn can bond to false if atom.bonded_to >= 3
# (that way primary atoms will be able to bond twice)

def change_R_groups(*dicts):
    import re

    t = open("test_file.txt", "w")
    for i in dicts:
        for key, value in i.items():
            t.write("\"" + key + "\":")
            t.write(" \"" + re.sub(r"\[R\]", "E", value) + "\",")
            t.write("\n")
        t.write("\n")

    t.close()

#change_R_groups(heterocycles, functionalized_arenes, functional_groups, hydrocarbons, amines, linkers, amino_acids)